### PR TITLE
Update peerDependencies to support Grunt 1.0

### PR DESCRIPTION
**Pull request by gruntjs-updater**
Update peerDependencies to support Grunt 1.0

Hello,

This is an automated issue request to update the `peerDependencies` for your Grunt plugin.
We ask you to merge this and **publish a new release on npm** to get your plugin working in Grunt 1.0!

Read more here: http://gruntjs.com/blog/2016-02-11-grunt-1.0.0-rc1-released#peer-dependencies
Also on Twitter: https://twitter.com/gruntjs/status/700819604155707392

If you have any questions or you no longer have time to maintain this plugin, then please let us know in this thread.

Thanks for creating and working on this plugin!

(P.S. Close this PR if it is a mistake, sorry)

### CODE REVIEW

**Comment by marcovtwout** [comment]
@tonyganch grunt 1.0.0 is here, and we can't install csscomb anymore. Please merge this pull request if possible.

**Comment by SuneRadich** [comment]
Any news on merging this PR?

**Comment by XhmikosR** [comment]
@tonyganch: ping, this is a breaking change. Can you merge this and publish a patch release?

**Comment by marcovtwout** [comment]
@mishanga, @tonyganch Anyone available to merge this PR? NPM v2 installs are failing and NPM v3 installs are throwing warnings.

**Comment by tvance** [comment]
Adding my vote to getting this updated. If this isn't an active project, please let users know -- this pull request has been out there for four months.

**Comment by franz-josef-kaiser** [comment]
Please! can this get merged? Can not use `npm shrinkwrap` any more due to this. Tests are successful, everything works (using Nodejs 5.9.1 here) and the PR is written…

**Comment by tonyganch** [comment]
@franz-josef-kaiser, merged, thanks for email

**Comment by XhmikosR** [comment]
We also need a new release please.

**Comment by XhmikosR** [comment]
@franz-josef-kaiser: can you bug @tonyganch via email to make a patch release, tag and npm?

**Comment by tonyganch** [comment]
@XhmikosR, already done :) Released as version 3.1.1

**Comment by XhmikosR** [comment]
Thanks!

**Comment by tonyganch** [comment]
Can you please confirm whether new package works for you or if it requires more changes?

**Comment by XhmikosR** [comment]
I'll check in a few hours and if something is wrong I'll let you know.

**Comment by XhmikosR** [comment]
@tonyganch: everything is fine, thanks!

**Pull request merged**
